[pyupdater]
app_name = "UI"  # 这里替换为你的实际应用名称，需和代码里配置一致
company_name = "WanAn"  # 替换为你的公司或个人标识等
version = "1.2"  # 初始版本号，后续更新时要修改这个版本号

[pyupdater.clients]
Client = {type = "http", url = ["https://github.com/584981015/UI/releases"]}  # 修改为你的 GitHub 仓库 releases 页面地址